services:
  mariadb:
    image: mariadb:latest
    container_name: mvp_db
    environment:
      MYSQL_ROOT_PASSWORD: csi3335rocks
      MYSQL_DATABASE: msGraph
    ports:
      - "3306:3306"
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mvp_backend
    ports:
      - "8080:8080" 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mvp_db:3306/msGraph
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: csi3335rocks
    depends_on:
      - mariadb
    networks:
      - app_network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mvp_frontend
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - NODE_ENV=production

  verifier:
    build:
      context: ./formalmethod
      dockerfile: Dockerfile
    container_name: mvp_formalverifier
    ports:
      - "9000:9000"
    networks:
      - app_network
    volumes:
      - verifier_cache:/tmp/ms_verifier_cache

volumes:
  mariadb_data:
  verifier_cache:

networks:
  app_network:
    driver: bridge
