services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces
    networks:
      - dev-network

  # mongo_db:
  #   image: mongo:latest
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: aeGis2026Rocks
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - dev-network

volumes:
  mongo_data:

networks:
  dev-network:
    driver: bridge