spring:
  data:
    mongodb:
      uri: mongodb://root:aeGis2026Rocks@cloudhub_mongo:27017/aegis?authSource=admin

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}