// src/config.js
export const env = {
  IR_SERVICE_URL: window._env_?.REACT_APP_IR_SERVICE_URL || process.env.REACT_APP_IR_SERVICE_URL,
  VERIFY_SERVICE_URL: window._env_?.REACT_APP_VERIFY_SERVICE_URL || process.env.REACT_APP_VERIFY_SERVICE_URL,
  COMPONENT_SERVICE_URL: window._env_?.REACT_APP_COMPONENT_SERVICE_URL || process.env.REACT_APP_COMPONENT_SERVICE_URL,
  VECTOR_SERVICE_URL: window._env_?.REACT_APP_VECTOR_SERVICE_URL || process.env.REACT_APP_VECTOR_SERVICE_URL,
  ANALYSIS_SERVICE_URL: window._env_?.REACT_APP_ANALYSIS_SERVICE_URL || process.env.REACT_APP_ANALYSIS_SERVICE_URL,
  TEST_SERVICE_URL: window._env_?.REACT_APP_TEST_SERVICE_URL || process.env.REACT_APP_TEST_SERVICE_URL,
  AEGIS_SERVICE_URL: window._env_?.REACT_APP_AEGIS_SERVICE_URL || process.env.REACT_APP_AEGIS_SERVICE_URL,
  REPO_SERVICE_URL: window._env_?.REACT_APP_REPO_SERVICE_URL || process.env.REACT_APP_REPO_SERVICE_URL,
  CHATBOT_SERVICE_URL: window._env_?.REACT_APP_CHATBOT_SERVICE_URL || process.env.REACT_APP_CHATBOT_SERVICE_URL,
  USER_SERVICE_URL: window._env_?.REACT_APP_USER_SERVICE_URL || process.env.REACT_APP_USER_SERVICE_URL,
  EXEC_SERVICE_URL: window._env_?.REACT_APP_EXEC_SERVICE_URL || process.env.REACT_APP_EXEC_SERVICE_URL,
  SLMBACKEND_SERVICE_URL: window._env_?.REACT_APP_SLMBACKEND_SERVICE_URL || process.env.REACT_APP_SLMBACKEND_SERVICE_URL,
  INTERNAL_SERVICE_KEY: window._env_?.REACT_APP_INTERNAL_SERVICE_KEY || process.env.REACT_APP_INTERNAL_SERVICE_KEY,
  PUBLIC_POSTHOG_KEY: window._env_?.REACT_APP_PUBLIC_POSTHOG_KEY || process.env.REACT_APP_PUBLIC_POSTHOG_KEY,
  PUBLIC_POSTHOG_HOST: window._env_?.REACT_APP_PUBLIC_POSTHOG_HOST || process.env.REACT_APP_PUBLIC_POSTHOG_HOST,
  IS_DEMO_VERSION: window._env_?.REACT_APP_IS_DEMO_VERSION || process.env.REACT_APP_IS_DEMO_VERSION,
};