import React from 'react';
import { Joyride, Step, EventData } from 'react-joyride';
import { ConduitTourTooltip } from '../../tour/ConduitTourTooltip';

interface TestTourProps {
    run: boolean;
    onFinish: () => void;
}

export const TestTour: React.FC<TestTourProps> = ({ run, onFinish }) => {   
    const steps: Step[] = [
        {
            target: 'body',
            content: (
                <div>
                    <h2 className="text-sm font-bold tracking-wider uppercase text-slate-200 mb-1">
                        Test Suite Executor
                    </h2>
                    <p className="text-[13px] text-slate-300 leading-relaxed font-medium mt-2">
                        Welcome to the Executor. Here you can review, modify, and execute the targeted tests generated by our AI based on your architectural vulnerabilities.
                    </p>
                </div>
            ),
            placement: 'center',
            skipBeacon: true
        },
        {
            target: '.tour-test-list',
            content: (
                <div>
                    <h3 className="text-[13px] font-bold text-white uppercase tracking-wide mb-2">
                        Test Scenarios
                    </h3>
                    <p className="text-[12px] text-slate-400">
                        This sidebar contains all the test scenarios generated for your pipeline. Click on any scenario to load its executable code into the editor.
                    </p>
                </div>
            ),
            placement: 'right'
        },
        {
            target: '.tour-environment-settings',
            content: (
                <div>
                    <h3 className="text-[13px] font-bold text-white uppercase tracking-wide mb-2">
                        Environment Settings
                    </h3>
                    <p className="text-[12px] text-slate-400">
                        Set your target base URL here, and inject valid Auth Tokens. These tokens will be automatically applied to the specific endpoints that require them during execution time.
                    </p>
                </div>
            ),
            placement: 'right'
        },
        {
            target: '.tour-code-editor',
            content: (
                <div>
                    <h3 className="text-[13px] font-bold text-white uppercase tracking-wide mb-2">
                        Live Code Editor
                    </h3>
                    <p className="text-[12px] text-slate-400">
                        Review the generated tests. You have full control to edit them manually before executing them against your target system.
                    </p>
                </div>
            ),
            placement: 'left'
        },
        {
            target: '.tour-test-play',
            content: (
                <div>
                    <h3 className="text-[13px] font-bold text-white uppercase tracking-wide mb-2">
                        Test Execution
                    </h3>
                    <p className="text-[12px] text-slate-400">
                        When you are ready, click on this button to execute the selected test (currently active in the editor).
                    </p>
                </div>
            ),
            placement: 'bottom'
        },
        {
            target: '.tour-execution-results',
            content: (
                <div>
                    <h3 className="text-[13px] font-bold text-white uppercase tracking-wide mb-2">
                        Execution Results
                    </h3>
                    <p className="text-[12px] text-slate-400">
                        Once you run a test, status codes, and assertion results will populate here, clearly showing if the vulnerability exists.
                    </p>
                </div>
            ),
            placement: 'top'
        }
    ];

    const handleJoyrideEvent = (data: EventData) => {
        if (data.status === 'finished' || data.status === 'skipped') {
            onFinish();
        }
    };

    return (
        <Joyride
            steps={steps}
            run={run}
            continuous={true} 
            onEvent={handleJoyrideEvent}
            tooltipComponent={ConduitTourTooltip} 
            options={{
                overlayColor: 'rgba(2, 6, 23, 0.85)', 
                zIndex: 10000,
            }}
        />
    );
};